#!/bin/sh
INVERSE=1

[ -z "$1" ] && return

. /lib/functions.sh

wifi_rfkill_set() {
	uci set wireless.$1.disabled=$ACTION
}

ACTION=$(( ($1+$INVERSE) %2 ))
config_load wireless
config_foreach wifi_rfkill_set wifi-device

uci commit wireless
wifi up
